//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruHavuzu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        public Dersler()
        {
            this.Konulars = new HashSet<Konular>();
            this.Sinavlars = new HashSet<Sinavlar>();
            this.Kullanicilars = new HashSet<Kullanicilar>();
        }
    
        public int DersId { get; set; }
        public string DersAdi { get; set; }
        public Nullable<bool> DersDurumu { get; set; }
    
        public virtual ICollection<Konular> Konulars { get; set; }
        public virtual ICollection<Sinavlar> Sinavlars { get; set; }
        public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }
    }
}
