//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruHavuzu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public Kullanicilar()
        {
            this.Taleplers = new HashSet<Talepler>();
            this.Derslers = new HashSet<Dersler>();
            this.Sinavlars = new HashSet<Sinavlar>();
            this.Sorulars = new HashSet<Sorular>();
        }
    
        public int KullaniciId { get; set; }
        public int KullaniciTurId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string KulAdi { get; set; }
        public string Sifre { get; set; }
        public string Email { get; set; }
        public Nullable<bool> KullaniciDurumu { get; set; }
    
        public virtual KullaniciTuru KullaniciTuru { get; set; }
        public virtual ICollection<Talepler> Taleplers { get; set; }
        public virtual ICollection<Dersler> Derslers { get; set; }
        public virtual ICollection<Sinavlar> Sinavlars { get; set; }
        public virtual ICollection<Sorular> Sorulars { get; set; }
    }
}
