//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruHavuzu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineSinavEntities : DbContext
    {
        public OnlineSinavEntities()
            : base("name=OnlineSinavEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dersler> Derslers { get; set; }
        public DbSet<Konular> Konulars { get; set; }
        public DbSet<Kullanicilar> Kullanicilars { get; set; }
        public DbSet<KullaniciTuru> KullaniciTurus { get; set; }
        public DbSet<Sinavlar> Sinavlars { get; set; }
        public DbSet<Sorular> Sorulars { get; set; }
        public DbSet<Talepler> Taleplers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<KullanicilarSinavlar> KullanicilarSinavlars { get; set; }
    }
}
