//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruHavuzu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinavlar
    {
        public Sinavlar()
        {
            this.Kullanicilars = new HashSet<Kullanicilar>();
            this.Sorulars = new HashSet<Sorular>();
            this.Taleplers = new HashSet<Talepler>();
        }
    
        public int SinavId { get; set; }
        public int DersId { get; set; }
        public string SinavAdi { get; set; }
        public int SoruSayisi { get; set; }
        public int SinavSuresi { get; set; }
        public System.DateTime SinavBaslamaTarihi { get; set; }
        public System.DateTime SinavBitisTarihi { get; set; }
        public Nullable<bool> SinavDurumu { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }
        public virtual ICollection<Sorular> Sorulars { get; set; }
        public virtual ICollection<Talepler> Taleplers { get; set; }
    }
}
