//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruHavuzu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        public Sorular()
        {
            this.Kullanicilars = new HashSet<Kullanicilar>();
            this.Sinavlars = new HashSet<Sinavlar>();
        }
    
        public int SoruId { get; set; }
        public string SoruMetni { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string E { get; set; }
        public string DogruCevap { get; set; }
        public string ZorlukDerecesi { get; set; }
        public int KonuId { get; set; }
        public bool SoruDurumu { get; set; }
    
        public virtual Konular Konular { get; set; }
        public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }
        public virtual ICollection<Sinavlar> Sinavlars { get; set; }
    }
}
