//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruHavuzu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talepler
    {
        public Talepler()
        {
            this.Sinavlars = new HashSet<Sinavlar>();
        }
    
        public int TalepId { get; set; }
        public string TalepTuru { get; set; }
        public int KullaniciId { get; set; }
        public string Aciklama { get; set; }
        public string Durum { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual ICollection<Sinavlar> Sinavlars { get; set; }
    }
}
